export {default as logo} from '../assets/images/AGS_hor_blackn.png'

export {default as home_demo} from '../assets/images/home/1.png'
export {default as home1} from '../assets/images/home/1-1.png'
export {default as home2} from '../assets/images/home/1-2.png'
export {default as home3} from '../assets/images/home/1-3.png'
export {default as home4} from '../assets/images/home/1-4.png'

export {default as footer1} from '../assets/images/footer/1-1.png'
export {default as footer2} from '../assets/images/footer/1-2.png'
export {default as footer3} from '../assets/images/footer/1-3.png'
export {default as footer4} from '../assets/images/footer/2.jpeg'

export {default as about_top} from '../assets/images/about/about_top.jpg'

export {default as clint_logo1} from '../assets/images/about/11.svg'
export {default as clint_logo2} from '../assets/images/about/12.svg'
export {default as clint_logo3} from '../assets/images/about/13.svg'
export {default as clint_logo4} from '../assets/images/about/15.svg'
export {default as clint_logo5} from '../assets/images/about/16.svg'
export {default as clint_logo6} from '../assets/images/about/17.svg'
export {default as clint_logo7} from '../assets/images/about/18.svg'
export {default as clint_logo8} from '../assets/images/about/1.webp'
export {default as clint_logo9} from '../assets/images/about/19.svg'
export {default as clint_logo10} from '../assets/images/about/20.svg'
export {default as clint_logo11} from '../assets/images/about/21.svg'
export {default as clint_logo12} from '../assets/images/about/22.svg'
export {default as clint_logo13} from '../assets/images/about/24.svg'
export {default as clint_logo14} from '../assets/images/about/25.svg'
export {default as clint_logo15} from '../assets/images/about/3.svg'
export {default as clint_logo16} from '../assets/images/about/4.svg'
export {default as clint_logo17} from '../assets/images/about/7.svg'
export {default as clint_logo18} from '../assets/images/about/9.svg'
export {default as clint_logo19} from '../assets/images/about/aa.png'

export {default as sanjeet} from '../assets/images/about/Sanjeet-Sharma-1-1738x2048.webp'
export {default as shobhit} from '../assets/images/about/Shobhit-Kumar-1753x2048.webp'
export {default as manish} from '../assets/images/about/Manish-Yadav-8702abe1.webp'

export {default as products_top} from '../assets/images/products/products_top.jpg'
export {default as products1} from '../assets/images/products/prods.png'
export {default as products2} from '../assets/images/products/prods2.png'
export {default as products3} from '../assets/images/products/floaTEM.png'
