export {default as logo} from '../assets/images/AGS_hor_blackn.png'

export {default as home_demo} from '../assets/images/home/1.png'
export {default as home1} from '../assets/images/home/1-1.png'
export {default as home2} from '../assets/images/home/1-2.png'
export {default as home3} from '../assets/images/home/1-3.png'
export {default as home4} from '../assets/images/home/1-4.png'

export {default as footer1} from '../assets/images/footer/1-1.png'
export {default as footer2} from '../assets/images/footer/1-2.png'
export {default as footer3} from '../assets/images/footer/1-3.png'
export {default as footer4} from '../assets/images/footer/2.jpeg'

export {default as about_top} from '../assets/images/about/about_top.jpg'

export {default as clint_logo1} from '../assets/images/about/11.svg'
export {default as clint_logo2} from '../assets/images/about/12.svg'
export {default as clint_logo3} from '../assets/images/about/13.svg'
export {default as clint_logo4} from '../assets/images/about/15.svg'
export {default as clint_logo5} from '../assets/images/about/16.svg'
export {default as clint_logo6} from '../assets/images/about/17.svg'
export {default as clint_logo7} from '../assets/images/about/18.svg'
export {default as clint_logo8} from '../assets/images/about/1.webp'
export {default as clint_logo9} from '../assets/images/about/19.svg'
export {default as clint_logo10} from '../assets/images/about/20.svg'
export {default as clint_logo11} from '../assets/images/about/21.svg'
export {default as clint_logo12} from '../assets/images/about/22.svg'
export {default as clint_logo13} from '../assets/images/about/24.svg'
export {default as clint_logo14} from '../assets/images/about/25.svg'
export {default as clint_logo15} from '../assets/images/about/3.svg'
export {default as clint_logo16} from '../assets/images/about/4.svg'
export {default as clint_logo17} from '../assets/images/about/7.svg'
export {default as clint_logo18} from '../assets/images/about/9.svg'
export {default as clint_logo19} from '../assets/images/about/aa.png'

export {default as sanjeet} from '../assets/images/about/Sanjeet-Sharma-1-1738x2048.webp'
export {default as shobhit} from '../assets/images/about/Shobhit-Kumar-1753x2048.webp'
export {default as manish} from '../assets/images/about/Manish-Yadav-8702abe1.webp'

export {default as products_top} from '../assets/images/products/products_top.jpg'
export {default as sTEM1} from '../assets/images/products/sTEM1.png'
export {default as sTEM2} from '../assets/images/products/sTEM2.png'
export {default as sTEM3} from '../assets/images/products/sTEM3.png'
export {default as sTEM4} from '../assets/images/products/sTEM4.png'
export {default as sTEM5} from '../assets/images/products/sTEM5.png'
export {default as sTEM6} from '../assets/images/products/sTEM6.png'
export {default as tTEM1} from '../assets/images/products/tTEM1.png'
export {default as tTEM2} from '../assets/images/products/tTEM2.png'
export {default as tTEM3} from '../assets/images/products/tTEM3.png'
export {default as floaTEM1} from '../assets/images/products/floaTEM1.png'
export {default as floaTEM2} from '../assets/images/products/floaTEM2.png'

export {default as geological} from '../assets/images/services/Geological/geological.png'
export {default as geophysical} from '../assets/images/services/Geophysical/geophysical.png'
export {default as geophysical1} from '../assets/images/services/Geophysical/geophysical1.png'
export {default as geophysical2} from '../assets/images/services/Geophysical/geophysical2.png'
export {default as geophysical3} from '../assets/images/services/Geophysical/geophysical3.png'
export {default as geospatial} from '../assets/images/services/Geospatial/geospatial.png'
export {default as hydrogeological} from '../assets/images/services/Hydrogeological/hydrogeological.png'
